# Generated by Django 4.2.6 on 2023-10-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
