# Generated by Django 4.2.6 on 2023-10-19 02:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('sender_name', models.CharField(max_length=50)),
                ('sender_address', models.CharField(max_length=10)),
                ('sender_email', models.EmailField(max_length=254)),
                ('reciever_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone_number', models.IntegerField(blank=True, null=True)),
                ('reciever_address', models.CharField(blank=True, max_length=50, null=True)),
                ('reciever_email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('departure_time', models.DateField(blank=True, null=True)),
                ('arrival_time', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=10, null=True)),
                ('tracking_number', models.CharField(max_length=10, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Dispatch'), (3, 'On the way'), (4, 'Delivered')], default='pending')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=10)),
                ('password', models.TextField(max_length=8)),
            ],
        ),
    ]
