# Generated by Django 4.2.6 on 2023-10-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0002_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Dispatch'), (3, 'On the way'), (4, 'Delivered')], default=1),
        ),
    ]
