# Generated by Django 4.2.6 on 2023-10-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processed'), (2, 'Dispatch'), (3, 'En route '), (4, 'Delivered')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA68bb98a4-cd4c-4910-ORDER', max_length=30, unique=True),
        ),
    ]
