# Generated by Django 4.2.6 on 2023-10-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0005_alter_order_status_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('Processed', 'Processed'), ('Dispatch', 'Dispatch'), ('En Route', 'En Route '), ('Delivered', 'Delivered')], default='processed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA0e96286e-373e-46ff-ORDER', max_length=30, unique=True),
        ),
    ]
