# Generated by Django 4.2.6 on 2023-10-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0006_alter_order_status_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processed'), (2, 'Dispatch'), (3, 'En Route '), (4, 'Delivered')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA7fc46c03-2bb1-4b2a-ORDER', max_length=30, unique=True),
        ),
    ]
