# Generated by Django 4.2.6 on 2023-10-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0008_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA427d2de1-b1b5-4520-ORDER', max_length=30, unique=True),
        ),
    ]
