# Generated by Django 4.2.6 on 2023-10-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0010_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA889cc7ae-8417-4e4a-ORDER', max_length=30, unique=True),
        ),
    ]
