# Generated by Django 4.2.6 on 2023-11-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0011_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA4d89ba42-72c0-42c2-ORDER', max_length=30, unique=True),
        ),
    ]
