# Generated by Django 4.2.6 on 2023-11-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0012_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA7182db40-9ca2-4c08-ORDER', max_length=30, unique=True),
        ),
    ]
