# Generated by Django 4.2.6 on 2023-11-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0013_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA909fabbf-e082-4707-ORDER', max_length=30, unique=True),
        ),
    ]
