# Generated by Django 4.2.6 on 2023-11-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0015_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA3ecc61f1-ac5e-4c40-ORDER', max_length=30, unique=True),
        ),
    ]
