# Generated by Django 3.2.23 on 2023-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0017_auto_20231126_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA0597c5b8-ec22-4034-ORDER', max_length=30, unique=True),
        ),
    ]
