# Generated by Django 3.2.23 on 2023-11-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0019_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA9b8bc41a-14ca-4a2c-ORDER', max_length=30, unique=True),
        ),
    ]
