# Generated by Django 3.2.23 on 2023-11-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0020_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA956400e4-43c5-464e-ORDER', max_length=30, unique=True),
        ),
    ]
