# Generated by Django 3.2.23 on 2024-03-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0021_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA2f066625-29a6-4a8f-ORDER', max_length=30, unique=True),
        ),
    ]
