# Generated by Django 3.2.23 on 2024-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0022_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA117d86ec-ab16-49a5-ORDER', max_length=30, unique=True),
        ),
    ]
