# Generated by Django 3.2.23 on 2024-05-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0023_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWAc886573e-28f1-4f92-ORDER', max_length=30, unique=True),
        ),
    ]
