# Generated by Django 3.2.23 on 2024-05-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0025_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA18c5b6cc-f9d1-4142-ORDER', max_length=30, unique=True),
        ),
    ]
