# Generated by Django 3.2.23 on 2024-05-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0026_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA9e06faad-a344-4542-ORDER', max_length=30, unique=True),
        ),
    ]
