# Generated by Django 3.2.23 on 2024-05-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0027_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA2a63acfb-081b-4382-ORDER', max_length=30, unique=True),
        ),
    ]
